[project]
name = "interai-traducoes"
version = "0.1.0"
description = "Add your description here"
dependencies = [
    "pandas>=2.2.2",
]
readme = "README.md"
requires-python = ">= 3.8"

[tool.rye]
managed = true
virtual = true
dev-dependencies = []
